/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Tablas_Model.AdmDatos;
import controlador.AdministradorJpaController;
import controlador.DoctorJpaController;
import controlador.SecretariaJpaController;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Administrador;
import modelo.Doctor;
import modelo.Secretaria;
import vistas.iAdministrador;
import vistas.iDoctor;
import vistas.iSecretaria;

/**
 *
 * @author abiga
 */
public class Login extends javax.swing.JFrame {
    private final AdmDatos adm;

    private final AdministradorJpaController cAdministradores;
    private final DoctorJpaController cDoctores;
    private final SecretariaJpaController cSecretarias;

    private final List<Administrador> administradores;
    private final List<Doctor> doctores;
    private final List<Secretaria> secretarias;
    
    private static Doctor doctorLogueado;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);

        adm = new AdmDatos();

        cAdministradores = new AdministradorJpaController(adm.getEmf());
        administradores = cAdministradores.findAdministradorEntities();

        cDoctores = new DoctorJpaController(adm.getEmf());
        doctores = cDoctores.findDoctorEntities();

        cSecretarias = new SecretariaJpaController(adm.getEmf());
        secretarias = cSecretarias.findSecretariaEntities();

        txtNombre.setEnabled(false);
        txtIdentificador.setEnabled(false);
        btnIngresar.setEnabled(false);

        getRootPane().setDefaultButton(btnIngresar);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelPsw = new javax.swing.JLabel();
        txtIdentificador = new javax.swing.JTextField();
        comboTipoUsuario = new javax.swing.JComboBox<>();
        btnIngresar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 244, 248));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel1.setText("SISTEMA DE GESTIÓN DE CITAS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Usuario");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");

        labelPsw.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPsw.setText("Password");

        comboTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione tipo de usuario", "Administrador", "Secretaria", "Doctor" }));
        comboTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoUsuarioActionPerformed(evt);
            }
        });

        btnIngresar.setBackground(new java.awt.Color(0, 123, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(comboTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPsw)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdentificador)))
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngresar)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPsw))
                .addGap(29, 29, 29)
                .addComponent(btnIngresar)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoUsuarioActionPerformed

        actualizarCampos();
    }//GEN-LAST:event_comboTipoUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        validarLogin();
    }//GEN-LAST:event_btnIngresarActionPerformed
    
    public static Doctor getDoctorLogueado() {
        return doctorLogueado;
    }

    public static void setDoctorLogueado(Doctor doctor) {
        doctorLogueado = doctor;
    }
    
    private void validarLogin() {
        String tipoUsuario = (String) comboTipoUsuario.getSelectedItem();
        String usuario = txtNombre.getText().trim();
        String psw = txtIdentificador.getText().trim();

        if (tipoUsuario == null || usuario.isEmpty() || psw.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
            return;
        }

        switch (tipoUsuario) {
            case "Administrador":
                for (Administrador a : administradores) {
                    if (a.getUsuario().equals(usuario) && a.getContrasena().equals(psw)) {
                        JOptionPane.showMessageDialog(this, "Bienvenido Administrador");
                        iAdministrador inter = new iAdministrador(a.getUsuario());
                        inter.setVisible(true);
                        this.dispose();
                        return;
                    }
                }
                break;
            case "Doctor":
                for (Doctor a : doctores) {
                    if (a.getUsuario().equals(usuario) && a.getContrasena().equals(psw)) {
                        setDoctorLogueado(a); // guardamos doctor logueado
                        JOptionPane.showMessageDialog(this, "Bienvenido Doctor");
                        iDoctor inter = new iDoctor(usuario);
                        inter.setVisible(true);
                        this.dispose();
                        return;
                    }
                }
                break;

            case "Secretaria":
                for (Secretaria a : secretarias) {
                    if (a.getUsuario().equals(usuario) && a.getContrasena().equals(psw)) {
                        JOptionPane.showMessageDialog(this, "Bienvenida");
                        iSecretaria inter = new iSecretaria(a.getUsuario(),a.getId());
                        inter.setVisible(true);
                        this.dispose();
                        return;
                    }
                }
                break;
        }

        JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.");
    }

    private void actualizarCampos() {
        String tipo = (String) comboTipoUsuario.getSelectedItem();
        if (tipo == null) return;

        if (!tipo.equals("Seleccione tipo de usuario")) {
            labelPsw.setText("Contraseña");
            txtNombre.setEnabled(true);
            txtIdentificador.setEnabled(true);
            btnIngresar.setEnabled(true);
        } else {
            txtNombre.setEnabled(false);
            txtIdentificador.setEnabled(false);
            btnIngresar.setEnabled(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> comboTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelPsw;
    private javax.swing.JTextField txtIdentificador;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
