/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

/**
 *
 * @author abiga
 */

import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;

public class PanelReloj extends javax.swing.JPanel {

    /**
     * Creates new form PanelReloj
     */
    
    private final SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
    private final SimpleDateFormat formatoFecha = new SimpleDateFormat("EEEE, d 'de' MMMM 'de' yyyy");
    
    public PanelReloj() {
        initComponents();
        setBackground(new Color(30, 30, 30));

        lblHora.setFont(new Font("Segoe UI", Font.BOLD, 80));
        lblHora.setForeground(Color.WHITE);
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblFecha.setFont(new Font("Segoe UI", Font.PLAIN, 28));
        lblFecha.setForeground(new Color(200, 200, 200));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        // Timer para actualizar cada segundo
        Timer timer = new Timer(1000, e -> actualizarFechaHora());
        timer.start();

        actualizarFechaHora(); // Inicial
    }
    
    private void actualizarFechaHora() {
        Date ahora = new Date();
        lblHora.setText(formatoHora.format(ahora));
        lblFecha.setText(formatoFecha.format(ahora));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();

        lblHora.setText("jLabel1");

        lblFecha.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFecha)
                    .addComponent(lblHora))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(lblHora)
                .addGap(43, 43, 43)
                .addComponent(lblFecha)
                .addContainerGap(203, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    // End of variables declaration//GEN-END:variables
}
