/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import Tablas_Model.AdmDatos;
import controlador.CitaJpaController;
import controlador.ConsultaJpaController;
import controlador.PacienteJpaController;
import javax.swing.JOptionPane;
import java.util.List;
import modelo.Cita;
import modelo.Consulta;
import modelo.Doctor;
import modelo.Paciente;

/**
 *
 * @author abiga
 */
public class rConsultas extends javax.swing.JPanel {

    private final Doctor doctorActual;
    private final CitaJpaController cCita;
    private final ConsultaJpaController cConsulta;
    private final PacienteJpaController cPaciente;

    private List<Cita> citasPendientes;
    private Cita citaSeleccionada;
    /**
     * Creates new form rTutorados
     */
    public rConsultas() {

        doctorActual = GUI.Login.getDoctorLogueado();

        initComponents();

        AdmDatos adm = new AdmDatos();
        cCita = new CitaJpaController(adm.getEmf());
        cConsulta = new ConsultaJpaController(adm.getEmf());
        cPaciente = new PacienteJpaController(adm.getEmf());

        habilitarCamposConsulta(false);
        cargarCitasPendientes();
    }
    
    private void cargarCitasPendientes() {
        lCitas.removeAllItems();
        lCitas.addItem("Selecciona cita");

        citasPendientes = cCita.findCitaEntities().stream()
                .filter(c -> c.getDoctorId().equals(doctorActual) 
                          && !"Realizada".equalsIgnoreCase(c.getEstado()))
                .toList();

        for (Cita c : citasPendientes) {
            String fechaHora = c.getFecha() + " " + c.getHora();
            lCitas.addItem("Cita #" + c.getIdcita() + " - " + fechaHora);
        }
    }
    private void habilitarCamposConsulta(boolean habilitar) {
        areaSintomas.setEnabled(habilitar);
        areaDiagnostico.setEnabled(habilitar);
        areaTratamiento.setEnabled(habilitar);
        AreaObservaciones.setEnabled(habilitar);
        Guardar.setEnabled(habilitar);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lCitas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnAceptar_tutor = new javax.swing.JButton();
        labelNombrePaciente = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaSintomas = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaDiagnostico = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaTratamiento = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        AreaObservaciones = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel1.setText("CONSULTAS");

        lCitas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        lCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lCitasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Selecciona Cita");

        btnAceptar_tutor.setText("Aceptar Cita");
        btnAceptar_tutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar_tutorActionPerformed(evt);
            }
        });

        labelNombrePaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombrePaciente.setText("Paciente: ");

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Sintomas");

        areaSintomas.setColumns(20);
        areaSintomas.setRows(5);
        jScrollPane1.setViewportView(areaSintomas);

        areaDiagnostico.setColumns(20);
        areaDiagnostico.setRows(5);
        jScrollPane2.setViewportView(areaDiagnostico);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Diagnóstico");

        areaTratamiento.setColumns(20);
        areaTratamiento.setRows(5);
        jScrollPane3.setViewportView(areaTratamiento);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Tratamiento");

        AreaObservaciones.setColumns(20);
        AreaObservaciones.setRows(5);
        jScrollPane4.setViewportView(AreaObservaciones);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Observaciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel6)
                .addGap(108, 108, 108)
                .addComponent(jLabel10)
                .addGap(91, 91, 91)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Guardar)
                .addGap(296, 296, 296))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(labelNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptar_tutor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel1)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lCitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAceptar_tutor)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(labelNombrePaciente)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(jLabel6))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12))))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(Guardar)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lCitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lCitasActionPerformed

    private void btnAceptar_tutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar_tutorActionPerformed
        if (lCitas.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Selecciona una cita");
            return;
        }

        citaSeleccionada = citasPendientes.get(lCitas.getSelectedIndex() - 1);

        Paciente paciente = citaSeleccionada.getPacienteId();
        labelNombrePaciente.setText("Paciente: " 
                + paciente.getPersonaId().getNombre() 
                + " " + paciente.getPersonaId().getApellido());

        habilitarCamposConsulta(true);
        lCitas.setEnabled(false);
        btnAceptar_tutor.setEnabled(false);
    }//GEN-LAST:event_btnAceptar_tutorActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        if (citaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Primero selecciona una cita");
            return;
        }

        try {
            Consulta consulta = new Consulta();
            consulta.setCitaId(citaSeleccionada);
            consulta.setSintomas(areaSintomas.getText().trim());
            consulta.setDiagnostico(areaDiagnostico.getText().trim());
            consulta.setTratamiento(areaTratamiento.getText().trim());
            consulta.setObservaciones(AreaObservaciones.getText().trim());

            cConsulta.create(consulta);

            // Cambiar estado de la cita a "Realizada"
            citaSeleccionada.setEstado("Realizada");
            cCita.edit(citaSeleccionada);

            JOptionPane.showMessageDialog(this, "Consulta guardada correctamente");

            // Reset campos
            areaSintomas.setText("");
            areaDiagnostico.setText("");
            areaTratamiento.setText("");
            AreaObservaciones.setText("");
            labelNombrePaciente.setText("Paciente: ");

            lCitas.setEnabled(true);
            btnAceptar_tutor.setEnabled(true);
            habilitarCamposConsulta(false);

            cargarCitasPendientes();
            citaSeleccionada = null;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar consulta: " + e.getMessage());
        }
    }//GEN-LAST:event_GuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaObservaciones;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextArea areaDiagnostico;
    private javax.swing.JTextArea areaSintomas;
    private javax.swing.JTextArea areaTratamiento;
    private javax.swing.JButton btnAceptar_tutor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> lCitas;
    private javax.swing.JLabel labelNombrePaciente;
    // End of variables declaration//GEN-END:variables
}
