/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import Tablas_Model.AdmDatos;
import controlador.PersonaJpaController;
import controlador.DoctorJpaController;
import controlador.SecretariaJpaController;
import controlador.AdministradorJpaController;
import controlador.PacienteJpaController;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Persona;
import modelo.Doctor;

/**
 *
 * @author abiga
 */
public class rDoctor extends javax.swing.JPanel {

    private Persona personaSeleccionada;
    private List<Persona> personas;
    private PersonaJpaController cPersona;
    private DoctorJpaController cDoctor;
    private SecretariaJpaController cSecretaria;
    private AdministradorJpaController cAdmin;
    private PacienteJpaController cPaciente;
    
    private final String SELECCIONA = "Selecciona persona";
    /**
     * Creates new form rTutorados
     */
    public rDoctor() {

        initComponents();

        AdmDatos adm = new AdmDatos();
        cPersona = new PersonaJpaController(adm.getEmf());
        cDoctor = new DoctorJpaController(adm.getEmf());
        cSecretaria = new SecretariaJpaController(adm.getEmf());
        cAdmin = new AdministradorJpaController(adm.getEmf());
        cPaciente = new PacienteJpaController(adm.getEmf());

        // Inicializar campos deshabilitados
        txtcedula.setEnabled(false);
        txtUsuario.setEnabled(false);
        txtcontrasena.setEnabled(false);
        boxEspecialidad.setEnabled(false);
        Guardar.setEnabled(false);
        Cancelar.setEnabled(false);

        // Cargar personas nuevas
        cargarPersonasNuevas();
    }
    
    public void cargarPersonasNuevas() {
        lPersona.removeAllItems();
        lPersona.addItem(SELECCIONA);

        personas = cPersona.findPersonaEntities();

        for (Persona p : personas) {
            boolean tieneDoctor = cDoctor.findDoctorEntities().stream().anyMatch(d -> d.getPersonaId().equals(p));
            boolean tieneSecretaria = cSecretaria.findSecretariaEntities().stream().anyMatch(s -> s.getPersonaId().equals(p));
            boolean tieneAdmin = cAdmin.findAdministradorEntities().stream().anyMatch(a -> a.getPersonaId().equals(p));
            boolean tienePaciente = cPaciente.findPacienteEntities().stream().anyMatch(pa -> pa.getPersonaId().equals(p));

            if (!tieneDoctor && !tieneSecretaria && !tieneAdmin && !tienePaciente) {
                lPersona.addItem(p.getNombre() + " " + p.getApellido());
            }
        }
    }
    
    private void cargarEspecialidades(){
        boxEspecialidad.removeAllItems();
        boxEspecialidad.addItem("Elegir"); // Primera opción no seleccionable
        boxEspecialidad.addItem("General");
        boxEspecialidad.addItem("Cardiología");
        boxEspecialidad.addItem("Pediatría");
        boxEspecialidad.addItem("Traumatología");
        boxEspecialidad.addItem("Ginecología");
        boxEspecialidad.addItem("Dermatología");
        boxEspecialidad.addItem("Neurología");
        boxEspecialidad.setSelectedIndex(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lPersona = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnAceptar_tutor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        boxEspecialidad = new javax.swing.JComboBox<>();
        txtcedula = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtcontrasena = new javax.swing.JPasswordField();
        Cancelar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel1.setText("Registrar Doctores");

        lPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        lPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lPersonaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Selecciona persona");

        btnAceptar_tutor.setText("Aceptar persona");
        btnAceptar_tutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar_tutorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Datos para el nuevo doctor");

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Cédula");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Usuario");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Contraseña");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Especialidad");

        boxEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "General", "Cardiología", "Pediatría", "Traumatología", "Ginecología", "Dermatología", "Neurología", " ", " " }));
        boxEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxEspecialidadActionPerformed(evt);
            }
        });

        txtcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaActionPerformed(evt);
            }
        });

        txtcontrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontrasenaActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptar_tutor))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(214, 214, 214)
                            .addComponent(Cancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Guardar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(156, 156, 156)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel9))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)))
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtcedula)
                                .addComponent(txtcontrasena)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(boxEspecialidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar_tutor)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(boxEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Cancelar))
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lPersonaActionPerformed

    private void btnAceptar_tutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar_tutorActionPerformed
        if(lPersona.getSelectedIndex() <= 0){
            JOptionPane.showMessageDialog(this, "Selecciona una persona");
            return;
        }

        int indice = lPersona.getSelectedIndex() - 1;
        personaSeleccionada = personas.get(indice);

        if (JOptionPane.showConfirmDialog(this, "¿Seleccionar a la persona " 
                + lPersona.getSelectedItem().toString() + "?") == JOptionPane.YES_OPTION) {

            // Habilitar campos de doctor
            txtcedula.setEnabled(true);
            txtUsuario.setEnabled(true);
            txtcontrasena.setEnabled(true);
            boxEspecialidad.setEnabled(true);
            Guardar.setEnabled(true);

            // Deshabilitar selección para no cambiar
            lPersona.setEnabled(false);
            btnAceptar_tutor.setEnabled(false);
        }
    }//GEN-LAST:event_btnAceptar_tutorActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        if(personaSeleccionada == null){
            JOptionPane.showMessageDialog(this, "Selecciona una persona primero.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Doctor nuevoDoctor = new Doctor();
        nuevoDoctor.setPersonaId(personaSeleccionada);
        nuevoDoctor.setLicenciamedica(txtcedula.getText().trim());
        nuevoDoctor.setUsuario(txtUsuario.getText().trim());
        nuevoDoctor.setContrasena(new String(txtcontrasena.getPassword()));
        nuevoDoctor.setEspecialidad(boxEspecialidad.getSelectedItem().toString());

        try {
            cDoctor.create(nuevoDoctor);
            JOptionPane.showMessageDialog(this, "Doctor registrado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // Reset campos
            txtcedula.setText("");
            txtUsuario.setText("");
            txtcontrasena.setText("");
            boxEspecialidad.setSelectedIndex(0);
            lPersona.setEnabled(true);
            btnAceptar_tutor.setEnabled(true);
            Guardar.setEnabled(false);

            // Recargar personas nuevas
            cargarPersonasNuevas();
            personaSeleccionada = null;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al registrar doctor: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void boxEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxEspecialidadActionPerformed

    private void txtcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaActionPerformed

    private void txtcontrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontrasenaActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        txtcedula.setText("");
        txtUsuario.setText("");
        txtcontrasena.setText("");
        lPersona.setSelectedIndex(0);
        boxEspecialidad.setSelectedIndex(0);
        lPersona.setEnabled(true);
        btnAceptar_tutor.setEnabled(true);
        
        txtcedula.setEnabled(false);
        txtUsuario.setEnabled(false);
        txtcontrasena.setEnabled(false);
        boxEspecialidad.setEnabled(false);
        Guardar.setEnabled(false);
    }//GEN-LAST:event_CancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Guardar;
    private javax.swing.JComboBox<String> boxEspecialidad;
    private javax.swing.JButton btnAceptar_tutor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> lPersona;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JPasswordField txtcontrasena;
    // End of variables declaration//GEN-END:variables
}
