/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import Tablas_Model.AdmDatos;
import controlador.PersonaJpaController;
import controlador.DoctorJpaController;
import controlador.SecretariaJpaController;
import controlador.AdministradorJpaController;
import controlador.PacienteJpaController;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Persona;
import modelo.Paciente;

/**
 *
 * @author abiga
 */
public class rPaciente extends javax.swing.JPanel {

    private Persona personaSeleccionada;
    private List<Persona> personas;
    private PersonaJpaController cPersona;
    private DoctorJpaController cDoctor;
    private SecretariaJpaController cSecretaria;
    private AdministradorJpaController cAdmin;
    private PacienteJpaController cPaciente;
    
    private final String SELECCIONA = "Selecciona persona";
    /**
     * Creates new form rTutorados
     */
    public rPaciente() {

        initComponents();

        AdmDatos adm = new AdmDatos();
        cPersona = new PersonaJpaController(adm.getEmf());
        cDoctor = new DoctorJpaController(adm.getEmf());
        cSecretaria = new SecretariaJpaController(adm.getEmf());
        cAdmin = new AdministradorJpaController(adm.getEmf());
        cPaciente = new PacienteJpaController(adm.getEmf());

        // Inicializar campos deshabilitados
        txtNSS.setEnabled(false);
        txtTipoSangre.setEnabled(false);
        lAlergias.setEnabled(false);
        Guardar.setEnabled(false);

        // Cargar personas nuevas
        cargarPersonasNuevas();

        // Cargar opciones de alergias
        cargarAlergias();
    }
    
    public void cargarPersonasNuevas() {
        lPersona.removeAllItems();
        lPersona.addItem(SELECCIONA);

        personas = cPersona.findPersonaEntities();

        for (Persona p : personas) {
            boolean tieneDoctor = cDoctor.findDoctorEntities().stream().anyMatch(d -> d.getPersonaId().equals(p));
            boolean tieneSecretaria = cSecretaria.findSecretariaEntities().stream().anyMatch(s -> s.getPersonaId().equals(p));
            boolean tieneAdmin = cAdmin.findAdministradorEntities().stream().anyMatch(a -> a.getPersonaId().equals(p));
            boolean tienePaciente = cPaciente.findPacienteEntities().stream().anyMatch(pa -> pa.getPersonaId().equals(p));

            if (!tieneDoctor && !tieneSecretaria && !tieneAdmin && !tienePaciente) {
                lPersona.addItem(p.getNombre() + " " + p.getApellido());
            }
        }
    }
    
     private void cargarAlergias() {
        lAlergias.removeAllItems();
        lAlergias.addItem("Elegir"); // Primera opción no seleccionable
        lAlergias.addItem("Ninguna");
        lAlergias.addItem("Polvo");
        lAlergias.addItem("Alimentos");
        lAlergias.addItem("Medicamentos");
        lAlergias.addItem("Animales");
        lAlergias.addItem("Otros");
        lAlergias.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lPersona = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnAceptar_tutor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lAlergias = new javax.swing.JComboBox<>();
        txtNSS = new javax.swing.JTextField();
        txtTipoSangre = new javax.swing.JTextField();
        Cancelar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel1.setText("Registrar Pacientes");

        lPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        lPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lPersonaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Selecciona persona");

        btnAceptar_tutor.setText("Aceptar persona");
        btnAceptar_tutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar_tutorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Datos para el nuevo paciente");

        Guardar.setText("Aceptar Paciente");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("NSS");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Tipo de sangre");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Alergias");

        lAlergias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "General", "Cardiología", "Pediatría", "Traumatología", "Ginecología", "Dermatología", "Neurología", " ", " " }));
        lAlergias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lAlergiasActionPerformed(evt);
            }
        });

        txtNSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNSSActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptar_tutor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Cancelar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel9))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNSS)
                                .addComponent(txtTipoSangre, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(lAlergias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Guardar))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar_tutor)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Cancelar))
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lPersonaActionPerformed

    private void btnAceptar_tutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar_tutorActionPerformed
        if(lPersona.getSelectedIndex() <= 0){
            JOptionPane.showMessageDialog(this, "Selecciona una persona");
            return;
        }

        int indice = lPersona.getSelectedIndex() - 1;
        personaSeleccionada = personas.get(indice);

        if (JOptionPane.showConfirmDialog(this, "¿Seleccionar a la persona " 
                + lPersona.getSelectedItem().toString() + "?") == JOptionPane.YES_OPTION) {

            // Habilitar campos de paciente
            txtNSS.setEnabled(true);
            txtTipoSangre.setEnabled(true);
            lAlergias.setEnabled(true);
            Guardar.setEnabled(true);

            // Deshabilitar selección para no cambiar
            lPersona.setEnabled(false);
            btnAceptar_tutor.setEnabled(false);
        }
    }//GEN-LAST:event_btnAceptar_tutorActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        if(personaSeleccionada == null){
            JOptionPane.showMessageDialog(this, "Selecciona una persona primero.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(lAlergias.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Selecciona un tipo de alergia válido.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Paciente nuevoPaciente = new Paciente();
        nuevoPaciente.setPersonaId(personaSeleccionada);
        nuevoPaciente.setNumerosegurosocial(txtNSS.getText().trim());
        nuevoPaciente.setTiposangre(txtTipoSangre.getText().trim());
        nuevoPaciente.setAlergias(lAlergias.getSelectedItem().toString());

        try {
            cPaciente.create(nuevoPaciente);
            JOptionPane.showMessageDialog(this, "Paciente registrado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // Reset campos
            txtNSS.setText("");
            txtTipoSangre.setText("");
            cargarAlergias();
            lPersona.setEnabled(true);
            btnAceptar_tutor.setEnabled(true);
            Guardar.setEnabled(false);

            // Recargar personas nuevas
            cargarPersonasNuevas();
            personaSeleccionada = null;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al registrar paciente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void lAlergiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lAlergiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lAlergiasActionPerformed

    private void txtNSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNSSActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        txtNSS.setText("");
        txtTipoSangre.setText("");
        cargarAlergias();
        lPersona.setEnabled(true);
        btnAceptar_tutor.setEnabled(true);
        Guardar.setEnabled(false);

        txtNSS.setEnabled(false);
        txtTipoSangre.setEnabled(false);
        lAlergias.setEnabled(false);
        Guardar.setEnabled(false);
    }//GEN-LAST:event_CancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton btnAceptar_tutor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> lAlergias;
    private javax.swing.JComboBox<String> lPersona;
    private javax.swing.JTextField txtNSS;
    private javax.swing.JTextField txtTipoSangre;
    // End of variables declaration//GEN-END:variables
}
