/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import Tablas_Model.AdmDatos;
import Tablas_Model.MtCitas;
import controlador.CitaJpaController;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import modelo.Cita;

/**
 *
 * @author abiga
 */
public class sCita extends javax.swing.JPanel {

    private AdmDatos adm;
    private CitaJpaController cCita;
    private List<Cita> citas;
    private MtCitas mcita;
    /**
     * Creates new form sCita
     */
    public sCita() {
        initComponents();
        
        adm = new AdmDatos();
        cCita = new CitaJpaController(adm.getEmf());
        citas = cCita.findCitaEntities();
        mcita = new MtCitas(citas);
        tablaCitas.setModel(mcita);

        labelTotal.setText("Total: " + tablaCitas.getRowCount() + " citas");
        
        
    }
    
public void windowActivated(WindowEvent e) {
    tablaCitas.setModel(mcita);
}

    
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboTipoFiltro = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCitas = new javax.swing.JTable();
        labelTotal = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel1.setText("Seguimiento Citas");

        comboTipoFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todo", "Activa", "Pendiente", "Cancelada", "Realizada" }));
        comboTipoFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoFiltroActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Filtro:");

        tablaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tutor", "Tutorado", "Fecha", "Hora", "Acciones"
            }
        ));
        jScrollPane1.setViewportView(tablaCitas);

        labelTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotal.setText("Total: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboTipoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(labelTotal)
                                .addGap(243, 243, 243))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboTipoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTotal))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void comboTipoFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoFiltroActionPerformed
        filtrarCitasPorEstado();
    }//GEN-LAST:event_comboTipoFiltroActionPerformed

    private void filtrarCitasPorEstado() {
        String filtro = (String) comboTipoFiltro.getSelectedItem();
        List<Cita> filtradas = new ArrayList<>();

        for (Cita c : citas) {
            String estado = c.getEstado();
            String estadoTexto = traducirEstado(estado);

            if (filtro.equals("Todo") || filtro.equals(estadoTexto)) {
                filtradas.add(c);
            }
        }

        mcita.setLista(filtradas);
        labelTotal.setText("Total: " + filtradas.size() + " citas");
    }

    private String traducirEstado(String estado) {
        if (estado == null) return "Desconocido";
        switch (estado) {
            case "0": return "Programada";
            case "1": return "Activa";
            case "2": return "Cancelada";
            case "3": return "Realizada";
            default: return estado;
        }
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboTipoFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JTable tablaCitas;
    // End of variables declaration//GEN-END:variables
}
