/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import Tablas_Model.AdmDatos;
import Tablas_Model.MTpersona;
import controlador.PersonaJpaController;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import modelo.Persona;


/**
 *
 * @author abiga
 */
public class sPersonas extends javax.swing.JPanel {
    
    private AdmDatos adm;
    private PersonaJpaController cPersona;
    private List<Persona> personas;
    private MTpersona mtPersona;

    /**
     * Creates new form sTutoria
     */
    public sPersonas() {
        initComponents();
       
        adm = new AdmDatos();
        cPersona = new PersonaJpaController(adm.getEmf());
        personas = cPersona.findPersonaEntities();

        mtPersona = new MTpersona(personas);
        tablePERSONAS.setModel(mtPersona);

        cargarDatos();
        
    }
    
    public void cargarDatos(){
        mtPersona = new MTpersona(personas);
        tablePERSONAS.setModel(mtPersona);
        tablePERSONAS.updateUI();
        comboPERSONAS.setEnabled(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboPERSONAS = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePERSONAS = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        comboTipoFiltro = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel1.setText("Seguimiento Personas");

        comboPERSONAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPERSONASActionPerformed(evt);
            }
        });

        tablePERSONAS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tutor", "Tutorado", "Fecha", "Hora", "Acciones"
            }
        ));
        jScrollPane1.setViewportView(tablePERSONAS);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Filtro:");

        comboTipoFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todo" }));
        comboTipoFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboTipoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(comboPERSONAS, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPERSONAS, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(comboTipoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboPERSONASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPERSONASActionPerformed
        // TODO add your handling code here:
        aplicarFiltro();
    }//GEN-LAST:event_comboPERSONASActionPerformed

    public void aplicarFiltro() {
        String tipo = (String) comboTipoFiltro.getSelectedItem();
        String valorSeleccionado = (String) comboPERSONAS.getSelectedItem();

        if (valorSeleccionado == null || valorSeleccionado.equals("TODO")) {
            mtPersona = new MTpersona(personas);
            tablePERSONAS.setModel(mtPersona);
            tablePERSONAS.updateUI();
            comboPERSONAS.setEnabled(false);
            return;
        }

        comboPERSONAS.setEnabled(true);

        List<Persona> filtradas = new ArrayList<>();
        for (Persona p : personas) {
            String valorComparar = "";
            switch (tipo) {
                case "Nombre": valorComparar = p.getNombre(); break;
                case "Apellido": valorComparar = p.getApellido(); break;
                case "Teléfono": valorComparar = p.getTelefono(); break;
                case "Email": valorComparar = p.getEmail(); break;
                case "Fecha Nacimiento": valorComparar = String.valueOf(p.getFechanacimiento()); break;
                case "Dirección": valorComparar = p.getDireccion(); break;
            }
            if (valorComparar.equals(valorSeleccionado)) {
                filtradas.add(p);
            }
        }

        mtPersona = new MTpersona(filtradas);
        tablePERSONAS.setModel(mtPersona);
        tablePERSONAS.updateUI();
    }



    private void comboTipoFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoFiltroActionPerformed
        // TODO add your handling code here:
        cargarValoresFiltro();
        comboPERSONAS.setEnabled(true);
    }//GEN-LAST:event_comboTipoFiltroActionPerformed

    public void cargarValoresFiltro() {
    comboPERSONAS.removeAllItems();
        comboPERSONAS.addItem("TODO");

        String tipo = (String) comboTipoFiltro.getSelectedItem();
        Set<String> valoresUnicos = new HashSet<>();

        for (Persona p : personas) {
            switch (tipo) {
                case "Nombre": valoresUnicos.add(p.getNombre()); break;
                case "Apellido": valoresUnicos.add(p.getApellido()); break;
                case "Teléfono": valoresUnicos.add(p.getTelefono()); break;
                case "Email": valoresUnicos.add(p.getEmail()); break;
                case "Fecha Nacimiento": valoresUnicos.add(String.valueOf(p.getFechanacimiento())); break;
                case "Dirección": valoresUnicos.add(p.getDireccion()); break;
            }
        }

        for (String valor : valoresUnicos) {
            comboPERSONAS.addItem(valor);
        }

        comboPERSONAS.setSelectedItem("TODO");
        comboPERSONAS.setEnabled(true);
}


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboPERSONAS;
    private javax.swing.JComboBox<String> comboTipoFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePERSONAS;
    // End of variables declaration//GEN-END:variables
}
